apiVersion: v1
appVersion: "3.8.0"
description: A Helm chart to install litmus gcp chaos experiments
name: kube-gcp
version: 3.8.0
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - gcp
  - kubernetes
maintainers:
  - name: jasstkn
    email: jasssstkn@yahoo.com
  - name: ksatchit
    email: karthik@chaosnative.com
  - name: uditgaurav
    email: udit@chaosnative.com
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
