# Default values for kubernetes
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "kube-gcp"
fullnameOverride: "kube-gcp"

# -- Additional labels
customLabels: {}

image:
  litmusGO:
    repository: litmuschaos.docker.scarf.sh/litmuschaos/go-runner
    tag: 3.20.0
    pullPolicy: Always

experiments:
  disabled: []
