apiVersion: v2
appVersion: "3.11.0"
description: A Helm chart to install ChaosCenter
name: litmus
version: 3.11.1
kubeVersion: ">=1.16.0-0"
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - kubernetes
maintainers:
  - name: imrajdas
    email: raj.das@mayadata.io
  - name: ispeakc0de
    email: shubham.chaudhary@mayadata.io
  - name: jasstkn
    email: jasssstkn@yahoo.com
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png

dependencies:
  - name: mongodb
    version: "12.1.11"
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: mongodb.enabled
