apiVersion: batch/v1
kind: Job
metadata:
  name: install-{{ include "litmus-agent.fullname" . }}
  labels:
    {{- include "litmus-agent.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "litmus-agent.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        imagePullPolicy: Always
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
        args: ["./litmus-agent", "--action", "create"]
        envFrom:
          - secretRef:
              {{- if .Values.existingHookSecret }}
              name: {{ .Values.existingHookSecret }}
              {{ else }}
              name: {{ include "litmus-agent.fullname" . }}-hook
              {{ end }}
        env:
          - name: AGENT_NAME
            value: {{ .Values.AGENT_NAME }}
          - name: AGENT_DESCRIPTION
            value: {{ .Values.AGENT_DESCRIPTION | quote }}
          - name: AGENT_MODE
            value: {{ .Values.global.AGENT_MODE }}
          - name: AGENT_CONFIGMAP_NAME
            value: {{ .Values.global.agentConfigName | quote }}
          - name: AGENT_SECRET_NAME
            value: {{ .Values.global.agentSecretName | quote }}
          - name: AGENT_NODE_SELECTOR
            value: {{ .Values.AGENT_NODE_SELECTOR | quote }}

          - name: PLATFORM_NAME
            value: {{ .Values.PLATFORM_NAME }}

          - name: SA_EXISTS
            value: {{ .Values.SA_EXISTS | quote }}

          - name: NS_EXISTS
            value: {{ .Values.NS_EXISTS | quote }}

          - name: CLUSTER_TYPE
            value: {{ .Values.CLUSTER_TYPE }}

          - name: RELEASE_NAME
            value: {{ .Release.Name }}

          - name: NAMESPACE
            value: {{ .Release.Namespace }}

          - name: APP_VERSION
            value: "3.0.0-beta3"

          - name: SERVICE_ACCOUNT_NAME
            value: {{ include "litmus-agent.serviceAccountName" . }}

          - name: WORKFLOW_CONTROLER_CONFIGMAP_NAME
            value: {{ index .Values "workflow-controller" "appSettings" "configmapName" }}
            
          - name: CONTAINER_RUNTIME_EXECUTOR
            value: {{ index .Values "workflow-controller" "appSettings" "containerRuntimeExecutor" | quote }}

        resources:
          {{- toYaml .Values.resources | nindent 10 }}
