{{- if and .Values.serviceAccount.create ( eq .Values.global.AGENT_MODE "cluster") -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "subscriber.serviceAccountName" . }}
  labels:
    {{- include "subscriber.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get","create","delete","update"]

- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get","list","watch"]

- apiGroups: [""]
  resources: ["pods","namespaces","nodes","services"]
  verbs: ["get","list","watch"]

- apiGroups: ["litmuschaos.io"]
  resources: ["chaosengines","chaosschedules","chaosresults"]
  verbs: ["get","list","create","delete","update","watch"]

- apiGroups: ["apps.openshift.io"]
  resources: ["deploymentconfigs"]
  verbs: ["get","list"]

- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get","list", "delete","deletecollection"]

- apiGroups: ["argoproj.io"]
  resources: ["workflows","workflows/finalizers","workflowtemplates", "workflowtemplates/finalizers","cronworkflows","cronworkflows/finalizers","clusterworkflowtemplates","clusterworkflowtemplates/finalizers","rollouts"]
  verbs: ["get","list","create","delete","update","watch"]
{{- end }}
