{{- if .Values.portal.server.authServer.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-auth-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
    {{- if .Values.portal.server.customLabels }}
      {{ toYaml .Values.portal.server.customLabels | nindent 4 }}
    {{- end }}
  name: {{ include "litmus-portal.fullname" . }}-auth-server
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "litmus-portal.fullname" . }}-auth-server
  minReplicas: {{ .Values.portal.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.portal.frontend.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.portal.frontend.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.portal.frontend.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ . }}
  {{- end }}
{{- end }}