apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "litmus-portal.fullname" . }}-auth-server'
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: '{{ include "litmus-portal.name" . }}-auth-server'
    {{- include "litmus-portal.labels" . | nindent 4 }}
    {{- if .Values.portal.server.customLabels }}
      {{ toYaml .Values.portal.server.customLabels | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.portal.server.authServer.autoscaling.enabled }}
  replicas: {{ .Values.portal.server.authServer.replicas }}
  {{- end }}
  {{- if .Values.portal.server.updateStrategy }}
  strategy:
  {{- toYaml .Values.portal.server.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-auth-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-auth-server
        {{- include "litmus-portal.labels" . | nindent 8 }}
        {{- if .Values.portal.server.customLabels }}
          {{ toYaml .Values.portal.server.customLabels | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ .Values.portal.server.authServer.automountServiceAccountToken }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-mongodb
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.server.waitForMongodb.image.repository }}:{{ .Values.portal.server.waitForMongodb.image.tag }}
          imagePullPolicy: {{ .Values.portal.server.waitForMongodb.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          env:
            - name: DB_PASSWORD
              {{- if .Values.mongodb.enabled }}
              {{- if not .Values.mongodb.auth.existingSecret }}
              value: {{ .Values.mongodb.auth.rootPassword | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.auth.existingSecret }}
                  key: mongodb-root-password
              {{- end }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_PASSWORD
              {{- end }}
            - name: DB_USER
              {{- if .Values.mongodb.enabled }}
              value: {{ .Values.mongodb.auth.rootUser }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_USER
              {{- end }}
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "litmus-portal.fullname" . }}-admin-config
                  key: DB_SERVER
          args:
            [
                "until  [[ $(mongosh -u ${DB_USER} -p ${DB_PASSWORD} ${DB_SERVER} --eval 'rs.status()' | grep 'ok' | wc -l) -eq 1 ]]; do sleep 5; echo 'Waiting for the MongoDB to be ready...'; done; echo 'Connection with MongoDB established'",
            ]
          resources:
            {{- toYaml .Values.portal.server.waitForMongodb.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.portal.server.waitForMongodb.securityContext | nindent 12 }}
      containers:
        - name: auth-server
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.server.authServer.image.repository }}:{{ .Values.portal.server.authServer.image.tag }}
          imagePullPolicy: {{ .Values.portal.server.authServer.image.pullPolicy }}
          ports:
            {{- toYaml .Values.portal.server.authServer.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.portal.server.authServer.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.portal.server.authServer.securityContext | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "litmus-portal.secretname" . }}
            - configMapRef:
                name: {{ include "litmus-portal.fullname" . }}-admin-config
          env:
            - name: DB_PASSWORD
              {{- if .Values.mongodb.enabled }}
              {{- if not .Values.mongodb.auth.existingSecret }}
              value: {{ .Values.mongodb.auth.rootPassword | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.auth.existingSecret }}
                  key: mongodb-root-password
              {{- end }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_PASSWORD
              {{- end }}
            - name: DB_USER
              {{- if .Values.mongodb.enabled }}
              value: {{ .Values.mongodb.auth.rootUser }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_USER
              {{- end }}
            - name: LITMUS_GQL_GRPC_ENDPOINT
              value: "{{ include "litmus-portal.fullname" . }}-server-service"
            - name: "LITMUS_GQL_GRPC_PORT"
              value: "{{ .Values.portal.server.graphqlServer.service.graphqlRpcServer.port }}"
              {{- if .Values.internalTLS.enabled }}
            - name: ENABLE_INTERNAL_TLS
              value: "true"
            - name: TLS_CERT_PATH
              value: "{{ .Values.internalTLS.certMountPath }}/tls.crt"
            - name: TLS_KEY_PATH
              value: "{{ .Values.internalTLS.certMountPath }}/tls.key"
            - name: CA_CERT_TLS_PATH
              value: "{{ .Values.internalTLS.certMountPath }}/ca.crt"
              {{- else }}
            - name: ENABLE_INTERNAL_TLS
              value: "false"
              {{- end }}
            - name: REST_PORT
              value: "{{ (index .Values.portal.server.authServer.ports 0).containerPort }}"
            - name: GRPC_PORT
              value: "{{ (index .Values.portal.server.authServer.ports 1).containerPort }}"
            - name: ALLOWED_ORIGINS
              value: "{{ .Values.allowedOrigins }}"
              {{- if has "auth-server" .Values.proxy.components }}
            - name: HTTP_PROXY
              value: "{{ .Values.proxy.httpProxy }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.proxy.httpsProxy }}"
            - name: NO_PROXY
              value: "{{ .Values.proxy.noProxy }}"
              {{- end }}
            {{- range $key, $val := .Values.portal.server.authServer.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
          {{- with .Values.portal.server.authServer.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            {{- if .Values.internalTLS.enabled }}
            - name: auth-server-internal-certs
              mountPath: {{ .Values.internalTLS.certMountPath }}
            {{- end }}
      volumes:
      {{- with .Values.portal.server.authServer.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        {{- if .Values.internalTLS.enabled }}
        - name: auth-server-internal-certs
          secret:
            secretName: {{ template "litmus-portal.internalTLS.authServer.secretName" . }}
        {{- end }}
    {{- with .Values.portal.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
