{{ if not .Values.administratorMode.enabled }}
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    name: {{ include "litmus.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
rules:
- apiGroups: ["","apps","batch","litmuschaos.io"]
  resources: ["pods","jobs","deployments","daemonsets","statefulsets","events","configmaps","services","chaosengines","chaosexperiments","chaosresults"]
  verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
{{ else if .Values.administratorMode.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "litmus.fullname" . }}-admin
  labels:
    name: {{ include "litmus.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
rules:
- apiGroups: ["","apps","batch","extensions","litmuschaos.io","openebs.io","storage.k8s.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults","cstorpools","cstorvolumereplicas","configmaps","secrets","pods","pods/exec","pods/log","pods/eviction","jobs","replicasets","deployments","daemonsets","statefulsets","persistentvolumeclaims","persistentvolumes","storageclasses","services","events"]
  verbs: ["create","delete","get","list","patch","update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","patch"]
{{ end }}
