{{ if eq .Values.operatorMode "namespaced" }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "litmus.fullname" . }}
  labels:
    name: {{ include "litmus.name" . }}
    instance: {{ .Release.Name  }}
    chart: {{ include "litmus.chart" . }}
    litmuschaos.io/version: {{ .Chart.AppVersion }}
rules:
- apiGroups: ["","apps","batch","extensions","litmuschaos.io", "argoproj.io"]
  resources: ["pods","pods/exec","pods/log","pods/eviction","jobs","deployments","daemonsets","statefulsets","events","configmaps","services","rollouts","chaosengines","chaosexperiments","chaosresults"]
  verbs: ["get","create","update","patch","delete","list","watch","deletecollection"]
{{ end }}
