apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "litmus-portal.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-server
    {{- include "litmus-portal.labels" . | nindent 4 }}
    {{- if .Values.portal.server.customLabels }}
      {{ toYaml .Values.portal.server.customLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.portal.server.replicas }}
  {{- if .Values.portal.server.updateStrategy }}
  strategy:
  {{- toYaml .Values.portal.server.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-server
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-server
        {{- include "litmus-portal.labels" . | nindent 8 }}
        {{- if .Values.portal.server.customLabels }}
          {{ toYaml .Values.portal.server.customLabels | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.portal.server.serviceAccountName }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
      volumes:
        {{- toYaml .Values.portal.server.graphqlServer.volumes | default "" | nindent 8 }}
      initContainers:
        - name: wait-for-mongodb
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.server.waitForMongodb.image.repository }}:{{ .Values.portal.server.waitForMongodb.image.tag }}
          imagePullPolicy: {{ .Values.portal.server.waitForMongodb.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            [
              {{- if .Values.mongodb.enabled }}
                "while [[ $(curl -sw '%{http_code}' http://{{ include "litmus-portal.mongodbServiceName" . }}:{{ .Values.mongodb.service.ports.mongodb }} -o /dev/null) -ne 200 ]]; do sleep 5; echo 'Waiting for the MongoDB to be ready...'; done; echo 'Connection with MongoDB established'",
              {{- else }}
                "while [[ $(curl -sw '%{http_code}' http://{{ include "litmus-portal.mongodbServiceName" . }}:{{ .Values.adminConfig.DB_PORT }} -o /dev/null) -ne 200 ]]; do sleep 5; echo 'Waiting for the MongoDB to be ready...'; done; echo 'Connection with MongoDB established'",              
              {{- end }}    
            ]
          resources:
            {{- toYaml .Values.portal.server.waitForMongodb.resources | nindent 12 }}
      containers:
        - name: graphql-server
          image: {{ .Values.image.imageRegistryName }}/{{ .Values.portal.server.graphqlServer.image.repository }}:{{ .Values.portal.server.graphqlServer.image.tag }}
          volumeMounts:
            {{- toYaml .Values.portal.server.graphqlServer.volumeMounts | default "" | nindent 12 }}
          imagePullPolicy: {{ .Values.portal.server.graphqlServer.image.pullPolicy }}
          ports:
            {{- toYaml .Values.portal.server.graphqlServer.ports | nindent 12 }}
          resources:
            {{- toYaml .Values.portal.server.graphqlServer.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.portal.server.graphqlServer.securityContext | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: gql-server
            {{- toYaml .Values.portal.server.graphqlServer.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: gql-server
            {{- toYaml .Values.portal.server.graphqlServer.readinessProbe | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "litmus-portal.secretname" . }}
            - configMapRef:
                name: {{ include "litmus-portal.fullname" . }}-admin-config
          env:
            - name: DB_PASSWORD
              {{- if .Values.mongodb.enabled }}      
              {{- if not .Values.mongodb.auth.existingSecret }}
              value: {{ .Values.mongodb.auth.rootPassword }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.auth.existingSecret }}
                  key: mongodb-root-password
              {{- end }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_PASSWORD
              {{- end }}
            - name: DB_USER
              {{- if .Values.mongodb.enabled }}
              value: {{ .Values.mongodb.auth.rootUser }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "litmus-portal.secretname" . }}
                  key: DB_USER
              {{- end }}
            - name: LITMUS_PORTAL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CHAOS_CENTER_SCOPE
              value: {{ .Values.portalScope }}
            - name: SERVER_SERVICE_NAME
              value: {{ include "litmus-portal.fullname" . }}-server-service
            - name: INGRESS
              value: "{{ .Values.ingress.enabled }}"
            - name: INGRESS_NAME
              value: "{{ .Values.ingress.name }}"
            - name: "LITMUS_AUTH_GRPC_ENDPOINT"
              value: "{{ include "litmus-portal.fullname" . }}-auth-server-service"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- $imageRegistry := .Values.image.imageRegistryName -}}
            {{- range $key, $val := .Values.portal.server.graphqlServer.imageEnv }}
            - name: {{ $key }}
              value: {{ $imageRegistry }}/{{ $val }}
            {{- end }}
            {{- range $key, $val := .Values.portal.server.graphqlServer.genericEnv }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
    {{- with .Values.portal.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.portal.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}