apiVersion: v1
kind: Service
metadata:
  name: litmusportal-frontend-service
  namespace:  {{ .Release.Namespace }}
spec:
  {{- if .Values.ingress.enable }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.portal.frontend.service.type }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.portal.frontend.service.port }}
      targetPort: {{ .Values.portal.frontend.service.targetPort }}
  selector:
    component: litmusportal-frontend
