apiVersion: v1
kind: Service
metadata:
  name: litmusportal-server-service
  namespace:  {{ .Release.Namespace }}
spec:
  {{- if eq .Values.portal.frontend.ingress.enabled true }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.portal.server.service.type }}
  {{- end }}  
  ports:
    - name: graphql-server
      port: {{ .Values.portal.server.service.graphqlServer.port }}
      targetPort: {{ .Values.portal.server.service.graphqlServer.targetPort }}
    - name: auth-server
      port: {{ .Values.portal.server.service.authServer.port }}
      targetPort: {{ .Values.portal.server.service.authServer.targetPort }}
  selector:
    component: litmusportal-server
