apiVersion: v1
appVersion: "3.13.0"
description: A Helm chart to install litmus infra components on Kubernetes
name: litmus-core
version: 3.13.0
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - kubernetes
maintainers:
  - name: ksatchit
    email: karthik.s@mayadata.io
  - name: chandankumar4
    email: chandan.kumar@zopsmart.com
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
