{{- if and (.Values.enabled) (.Values.serviceMonitor.enabled)}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chaos-exporter.fullname" . }}
  labels:
    {{- include "chaos-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chaos-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 120s
    scrapeTimeout: 30s
  targetLabels:
    - name
{{- end }}