{{ if eq .Values.portalScope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: litmus-server-rb
subjects:
  - kind: ServiceAccount
    name: litmus-server-account
    namespace:  {{ .Values.portalNamespace }}
roleRef:
  kind: ClusterRole
  name: litmus-server
  apiGroup: rbac.authorization.k8s.io
{{ end }}