apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: { { include "litmus-portal.fullname" . } }-mongo
  namespace: { { .Release.Namespace } }
  labels:
    { { - include "litmus-portal.labels" . | nindent 4 } }
    app.kubernetes.io/part-of: { { include "litmus-portal.fullname" . } }-mongo
spec:
  selector:
    matchLabels:
      {{- include "litmus-portal.selectors" . | nindent 6 }}
      app.kubernetes.io/part-of: {{ include "litmus-portal.fullname" . }}-mongo
  serviceName: mongo
  replicas: {{ .Values.mongo.replicas }}
  template:
    metadata:
      labels:
        {{- include "litmus-portal.selectors" . | nindent 6 }}
        app.kubernetes.io/part-of: {{ include "litmus-portal.fullname" . }}-mongo
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
      { { - end } }
      containers:
        - name: mongo
          image: {{ .Values.mongo.image.repository }}:{{ .Values.mongo.image.tag }}
          ports:
            - containerPort: { { .Values.mongo.containerPort } }
              name: http
          imagePullPolicy: {{ .Values.mongo.image.pullPolicy }}
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "litmus-portal.fullname" . }}-admin-config
                  key: DB_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "litmus-portal.fullname" . }}-admin-config
                  key: DB_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        { { - if $persistence.storageClass } }
        storageClassName: { { $persistence.storageClass } }
        { { - end } }
        accessModes:
          - {{ $persistence.accessMode }}
        resources:
          requests:
            storage: {{ $persistence.size }}