global:
  agentConfigName: agent-config
  agentSecretName: agent-secret
  podAnnotations: {}
  # AGENT_MODE: cluster, namespace
  AGENT_MODE: "cluster"
# Default values for litmus-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
AGENT_NAME: "helm-agent"
AGENT_DESCRIPTION: "chaos agent deployed with helm"

AGENT_NODE_SELECTOR: ""
SA_EXISTS: true
NS_EXISTS: true
CLUSTER_TYPE: "external"

# PLATFORM_NAME: AWS, GKE, Openshift, Rancher, Others
PLATFORM_NAME: "Others"

LITMUS_URL: "https://my-domain.com"
LITMUS_BACKEND_URL: ""
LITMUS_USERNAME: "admin"
LITMUS_PASSWORD: "litmus"
LITMUS_PROJECT_ID: ""

image:
  repository: litmuschaos/litmus-helm-agent
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

crds:
  create: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Custom secret name should be:
# `{{ include "subscriber.fullname" . }}-hook`
# I.E. `name: litmus-agent-hook`
# -- Use an existing hook secret instead of creating one with the chart, ref. to templates/secret.yaml
useExistingHookSecret: false

chaos-operator:
  enabled: true

chaos-exporter:
  enabled: true

event-tracker:
  enabled: true

subscriber:
  enabled: true

workflow-controller:
  enabled: true
  crds:
    create: true
