apiVersion: v1
appVersion: "1.8.2"
description: A Helm chart to install litmus chaos experiments for kubernetes category (chaos-chart)
name: kubernetes-chaos
version: 2.2.3
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - kubernetes
maintainers:
  - name: ksatchit
    email: karthik.s@mayadata.io
  - name: chandankumar4
    email: chandan.kumar@mayadata.io
  - name: jasstkn
    email: jasssstkn@yahoo.com
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
