# Default values for kubernetes 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "k8s"
fullnameOverride: "k8s"

image:
  litmus: 
    repository: litmuschaos/ansible-runner
    tag: 1.6.1
    pullPolicy: Always

  litmusGO:
    repository: litmuschaos/go-runner
    tag: 1.6.2
    pullPolicy: Always

  pumba:
    libName: pumba

  litmusLIBImage:
    repository: litmuschaos/go-runner
    tag: 1.6.2

  networkChaos:
    tcImage: gaiadocker/iproute2
