# Default values for kubernetes
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "k8s"
fullnameOverride: "k8s"

image:
  litmus:
    repository: litmuschaos/ansible-runner
    tag: 1.8.0
    pullPolicy: Always

  litmusGO:
    repository: litmuschaos/go-runner
    tag: 1.8.1
    pullPolicy: Always

  pumba:
    libName: pumba

  litmusLIBImage:
    repository: litmuschaos/go-runner
    tag: 1.8.1

  networkChaos:
    tcImage: gaiadocker/iproute2

  stressChaos:
    stressImage: gaiaadm/pumba

environment:
  # supported: 'docker', 'containerd', 'crio'
  runtime: 'docker'

  # ex: '/var/run/docker.sock', '/run/containerd/containerd.sock', '/run/crio/crio.sock'
  socketPath: '/var/run/docker.sock'

  # ex: '/var/lib/docker/containers', '/var/lib/containerd/io.containerd.runtime.v1.linux/k8s.io', '/var/lib/containers/storage/overlay/'
  containerPath: '/var/lib/docker/containers'


experiments:
  disabled: []
