apiVersion: v1
appVersion: "2.2.0"
description: A Helm chart to install litmus aws chaos experiments
name: kube-aws
version: 1.18.0
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - aws
  - kubernetes
maintainers:
  - name: jasstkn
    email: jasssstkn@yahoo.com
  - name: ksatchit
    email: karthik@chaosnative.com    
  - name: uditgaurav
    email: udit@chaosnative.com
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
