# Default values for kubernetes
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "kube-aws"
fullnameOverride: "kube-aws"

# -- Additional labels
customLabels: {}

image:
  litmusGO:
    repository: litmuschaos/go-runner
    tag: 1.13.6
    pullPolicy: Always

experiments:
  disabled: []
