apiVersion: v1
appVersion: "2.0.0"
description: A Helm chart to install litmus portal
name: litmus-2-0-0-beta
version: 2.0.1-Beta1
home: https://litmuschaos.io
sources:
  - https://github.com/litmuschaos/litmus
keywords:
  - chaos-engineering
  - resiliency
  - kubernetes
maintainers:
  - name: rajdas98
    email: raj.das@mayadata.io
  - name: ispeakc0de
    email: shubham.chaudhary@mayadata.io
icon: https://raw.githubusercontent.com/litmuschaos/icons/master/litmus.png
